permalink: /:categories/:year/:month/:day/:title
exclude: ['.rvmrc', '.rbenv-version', 'README.md', 'Rakefile', 'changelog.md']
auto: true
pygments: true
markdown: redcarpet

title : Elegant Ruby
tagline: Notes on writing elegant, performant ruby code.
authors:
  ryan:
    name: Ryan Twomey
    email: rtwomey@gmail.com
    github: rtwomey
    twitter: rtwomey
    gravatar: f1c3b210bbbce4839610fab1a3e75764
  costa:
    name: Costa Walcott
    email: cwalcott@gmail.com
    github: cwalcott
    twitter: cwalcott
    gravatar: 21bcd9b02cc77dd3134a0e1c90402181

production_url : http://www.elegantruby.com

JB :
  version : 0.2.13

  BASE_PATH : false
  ASSET_PATH : false

  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html

  comments :
    provider : disqus
    disqus :
      short_name : elegantruby

  analytics :
    provider : google
    google :
        tracking_id : 'UA-37962858-1'

  # Settings for sharing helper.
  # Sharing is for things like tweet, plusone, like, reddit buttons etc.
  # Set 'provider' to the sharing provider you want to use.
  # Set 'provider' to false to turn sharing off globally.
  #
  sharing :
    provider : false
